### ISSUE TITLE
problem loading in 0.4.9

### ISSUE THREAD

**Issue by cesarpachon** [sapier/adv_spawning#1]
hello, just trying this mod to run animals_modpack in minetest 0.4.9, ubuntu, but fails loading: 

 ========== ERROR FROM LUA ===========
20:04:43: ERROR[main]: Failed to load and run script from 
20:04:43: ERROR[main]: /home/cesar/.minetest/mods/mobf/init.lua:
20:04:43: ERROR[main]: /home/cesar/.minetest/mods/mobf/init.lua:25: attempt to index global 'core' (a nil value)
20:04:43: ERROR[main]: stack traceback:
20:04:43: ERROR[main]: 	/home/cesar/.minetest/mods/mobf/init.lua:25: in main chunk
20:04:43: ERROR[main]: ======= END OF ERROR FROM LUA ========
20:04:43: ERROR[main]: Server: Failed to load and run /home/cesar/.minetest/mods/mobf/init.lua
20:04:43: ERROR[main]: ModError: ModError: Failed to load and run /home/cesar/.minetest/mods/mobf/init.lua
I tried renaming "core." by "minetest." (dont really know how I figure this, LOL) and it passed the errors on adv_spawning, but then appears lot of errors in mobf.

**Comment by sapier** [comment]
adv_spawning ain't capable of beeing used at minetest 0.4.9 sorry wont add compatibility please update mintest.
